//
//  NSDictionary+Http.m
//  8a-ios
//
//  Created by Kristoffer Yap on 4/21/17.
//  Copyright © 2017 Allfree Group LLC. All rights reserved.
//

#import "NSDictionary+Http.h"
#import "NSString+URL.h"

@implementation NSDictionary (Http)

/**
 Loops trough each [key: value] pair in self.
 
 :param: eachFunction Function to inovke on each loop
 */
- (void)each: (void(^)(id Key, id Value))eachFunction {
    
    for (id key in [self allKeys]) {
        id value = [self objectForKey:key];
        eachFunction(key, value);
    }
}

/**
 Creates an Array with strings generated by running
 each [key: value] of self through the mapFunction.
 
 :param: mapFunction
 :returns: Mapped array
 */
- (NSArray *)mapArray:(NSString *(^)(id Key, id Value))mapFunction {
    
    NSMutableArray *mapped = [[NSMutableArray alloc] init];
    [self each:^(id Key, id Value) {
        NSString *str = mapFunction(Key, Value);
        [mapped addObject:str];
    }];
    
    return mapped;
}

/// Build string representation of HTTP parameter dictionary of keys and objects
///
/// This percent escapes in compliance with RFC 3986
///
/// http://www.ietf.org/rfc/rfc3986.txt
///
/// :returns: String representation in the form of key1=value1&key2=value2 where the keys and values are percent escaped


- (NSString *)stringFromHttpParameters {
    NSArray *parameterArray = [self mapArray:^NSString *(id Key, id Value) {
        NSString *percentEscapedKey = [((NSString *)Key) stringByAddingPercentEncodingForURLQueryValue];
        NSString *percentEscapedValue = [((NSString *)Value) stringByAddingPercentEncodingForURLQueryValue];
        
        return [NSString stringWithFormat:@"%@=%@", percentEscapedKey, percentEscapedValue];
    }];
    
    return [parameterArray componentsJoinedByString:@"&"];
}

@end
